{
 "title": "Docker and system monitoring",
 "description": "A simple overview of the most important Docker host and container metrics. (cAdvisor/Node Exporter/Prometheus) updated from ID 893 by Thibaut Mottet",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "server",
    "label": "Node",
    "query": {
     "query": "label_values({\"$server\"},$server)"
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "label_values(dockerstats_cpu_usage_ratio,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Block Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "promtail_custom_block_processed_after_seconds",
     "legendFormat": "{{container_id}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "-sum(rate(node_disk_read_bytes_total[$interval])) by (device)",
     "legendFormat": "OUT on /{{device}}"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total[$interval])) by (device)",
     "legendFormat": "IN on /{{device}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(dockerstats_cpu_usage_ratio{job=\"docker-stats-exporter\", name=~\"$container\"}[$__rate_interval])\n) * 100\n",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum(rate(dockerstats_blockio_written_bytes{name=~\"$container\"}[$interval])/1024) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum(rate(dockerstats_blockio_read_bytes{name=~\"$container\"}[$interval])/1024) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Block Difficulty",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "promtail_custom_block_difficulty / 1000000000000000",
     "legendFormat": "{{container_id}}"
    }
   ]
  },
  {
   "title": "Gas Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 14 },
   "targets": [
    { "expr": "promtail_custom_block_gas_used", "legendFormat": "{{container_id}}" },
    {
     "expr": "promtail_custom_block_gas_limit",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Datasource Flush",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "promtail_custom_block_datasource_flush_seconds\n",
     "legendFormat": "{{container_id}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(dockerstats_network_received_bytes{name=~\"$container\"}[$interval])) by (name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "- sum(rate(dockerstats_network_transmitted_bytes{name=~\"$container\"}[$interval])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(dockerstats_network_transmitted_bytes{name=~\"$container\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(dockerstats_network_received_bytes{name=~\"$container\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[$interval])) * 100",
     "legendFormat": "host"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\".*\"}",
     "legendFormat": "{{server}}_15m"
    },
    {
     "expr": "node_load5{instance=~\".*\"}",
     "legendFormat": "_5m"
    },
    {
     "expr": "node_load15{instance=~\".*\"}",
     "legendFormat": "_15m"
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "node_load1{instance=~'.*'}" }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=~\".*\"} - node_filesystem_free_bytes{fstype=~\"xfs|ext4\",instance=~\".*\"} )/ node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=~\".*\"})"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(dockerstats_memory_usage_bytes{name=~\"$container\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(dockerstats_cpu_usage_ratio{name=~\"rskj.*\"}[$interval]))"
    }
   ]
  }
 ]
}